version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
volumes:
  mongodb-data:
